spring.application.name=urlShortener
server.port=8109

# Docker Compose Lifecycle Management
spring.docker.compose.lifecycle-management = start-only

# Since docker compose is used for running the application, the datasource is configured in docker-compose.yml. Even if configured here, it will be overridden by docker-compose settings.
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Configuration, not advised for production
#spring.jpa.hibernate.ddl-auto=update

# To avoid LazyInitializationException and improve performance by avoiding N+1 select issues. Make it false to improve performance
spring.jpa.open-in-view=false

# Fix timezone issue
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.show-sql=true

#For initializing the database with schema and data SQL files, not advised for production
#spring.sql.init.mode=always

#Configuration application properties
app.base-url=http://localhost:8109
app.default-expiry-in-days=30
app.validate-url=true
app.page-size=10

#Security properties
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.user.roles=USER,ADMIN